#!/usr/bin/env bash

export HOMEBREW_CASK_OPTS="--appdir=/Applications --prefpanedir=/Library/PreferencePanes --qlplugindir=/Library/QuickLook --fontdir=/Library/Fonts"
#set -x HOMEBREW_CASK_OPTS "--appdir=/Applications --prefpanedir=/Library/PreferencePanes --qlplugindir=/Library/QuickLook --fontdir=/Library/Fonts"

brew install caskroom/cask/brew-cask
brew cask install adobe-reader
#brew cask install alfred
brew cask install android-file-transfer
brew cask install atom
brew cask install caffeine
brew cask install coconutbattery
brew cask install disk-inventory-x
brew cask install dropbox
brew cask install flux
brew cask install google-chrome --caskroom=/Applications
brew cask install google-cloud-sdk
brew cask install google-drive
brew cask install handbrake
brew cask install imagealpha
brew cask install imageoptim
brew cask install iterm2
brew cask install mactracker
#brew cask install microsoft-office
#brew cask install rescuetime
brew cask install screenhero
brew cask install skype
brew cask install slack
brew cask install spotify
brew cask install sourcetree
brew cask install tomighty
brew cask install vagrant
brew cask install virtualbox
brew cask install viscosity
brew cask install vlc
brew cask install vmware-fusion
